# Generated by Django 5.0.7 on 2024-12-02 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_mentor_list_delete_mentor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('expertise', models.CharField(max_length=200)),
                ('bio', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Mentor_List',
        ),
    ]
