# Generated by Django 5.1 on 2024-12-26 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_mentor_delete_mentor_list'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mentor',
        ),
    ]
